// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

import (
	"database/sql"
)

type Customer struct {
	Uid                string         `json:"uid"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	Email              string         `json:"email"`
	Phone              sql.NullString `json:"phone"`
	FirstName          sql.NullString `json:"first_name"`
	LastName           sql.NullString `json:"last_name"`
	PhotoUrl           sql.NullString `json:"photo_url"`
	BhcPlotNumber      sql.NullString `json:"bhc_plot_number"`
	IsExistingCustomer sql.NullBool   `json:"is_existing_customer"`
}
