// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

import (
	"time"
)

type Customer struct {
	Uid                string    `json:"uid"`
	CreatedAt          time.Time `json:"created_at"`
	Email              string    `json:"email"`
	Phone              string    `json:"phone"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	PhotoUrl           string    `json:"photo_url"`
	BhcPlotNumber      string    `json:"bhc_plot_number"`
	IsExistingCustomer bool      `json:"is_existing_customer"`
}
